In [1]:
import pandas as pd
import numpy as np

In [2]:
chicago_listings = pd.read_csv(r"E:\PowerBI_Projects\Airbnb_Dashboard_Project\data\chicago_listings.csv")
chicago_reviews = pd.read_csv(r"E:\PowerBI_Projects\Airbnb_Dashboard_Project\data\chicago_reviews.csv")

new_orleans_listings = pd.read_csv(r"E:\PowerBI_Projects\Airbnb_Dashboard_Project\data\new_orleans_listings.csv")
new_orleans_reviews = pd.read_csv(r"E:\PowerBI_Projects\Airbnb_Dashboard_Project\data\new_orleans_reviews.csv")

In [3]:
chicago_listings.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,2384,Hyde Park - Walk to University of Chicago,2613,Rebecca,NaN,Hyde Park,41.787900,-87.587800,Private room,119.0,3,257,2025-08-07,1.97,1,348,10,R17000015609
1,7126,Tiny Studio Apartment 94 Walk Score,17928,Sarah,NaN,West Town,41.901660,-87.680210,Entire home/apt,89.0,2,595,2025-09-01,3.01,1,302,47,R24000114046
2,10945,The Biddle House (#1),33004,At Home Inn,NaN,Lincoln Park,41.911960,-87.639810,Entire home/apt,203.0,4,129,2025-09-06,0.93,6,325,24,2209984
3,12140,Lincoln Park Guest House,46734,Shar And Robert,NaN,Lincoln Park,41.923570,-87.649470,Private room,339.0,2,19,2025-09-07,0.15,1,156,3,2398451
4,28749,Quirky Bucktown Loft w/ Parking No Parties,27506,Lauri,NaN,Logan Square,41.920226,-87.679613,Entire home/apt,258.0,2,265,2025-09-01,1.47,1,74,37,R24000113825

In [4]:
chicago_listings.shape

(8663, 18)

In [5]:
chicago_listings.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='object')

In [6]:
chicago_listings.isnull().sum()

id                                   0
name                                 0
host_id                              0
host_name                          621
neighbourhood_group               8663
neighbourhood                        0
latitude                             0
longitude                            0
room_type                            0
price                              835
minimum_nights                       0
number_of_reviews                    0
last_review                       1685
reviews_per_month                 1685
calculated_host_listings_count       0
availability_365                     0
number_of_reviews_ltm                0
license                           2880
dtype: int64

In [7]:
# Remove neighbourhood_group column
chicago_listings = chicago_listings.drop(columns=['neighbourhood_group'])

# Fill missing host names
chicago_listings['host_name'] = chicago_listings['host_name'].fillna("Unknown")

# Replace missing reviews_per_month with 0
chicago_listings['reviews_per_month'] = chicago_listings['reviews_per_month'].fillna(0)

# Replace missing last_review
chicago_listings['last_review'] = chicago_listings['last_review'].fillna("No Review")

# Fill missing price with median
chicago_listings['price'] = chicago_listings['price'].fillna(chicago_listings['price'].median())

# Replace missing license
chicago_listings['license'] = chicago_listings['license'].fillna("Not Available")

In [8]:
chicago_listings.isnull().sum()

id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
number_of_reviews_ltm             0
license                           0
dtype: int64

In [9]:
new_orleans_listings.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,19091,Fully Furnished Cozy Apartment,72880,John,NaN,Leonidas,29.96100,-90.11950,Entire home/apt,61.0,1,510,2025-08-31,2.72,1,331,7,"25-NSTR-11772, 25-OSTR-11151"
1,71624,Ravenwood Manor (Historic Bywater),367223,Susan,NaN,Bywater,29.96153,-90.04364,Entire home/apt,150.0,30,316,2025-05-07,1.78,1,356,7,"21-RSTR-18609, 22-OSTR-20720"
2,74498,Maison Marais 1,391462,Georgia,NaN,St. Roch,29.96986,-90.05172,Entire home/apt,85.0,3,662,2025-06-29,3.75,3,231,28,23-XSTR-13082
3,79536,FeelAtHomeInNewOrleans-PrivateApt,428362,Miriam,NaN,Seventh Ward,29.97803,-90.07450,Entire home/apt,NaN,3,799,2025-09-04,4.57,1,0,68,"23-NSTR-15067, 24-OSTR-20882"
4,79609,Bywater's Original & Finest,428909,Stephen,NaN,St. Claude,29.96448,-90.03667,Entire home/apt,84.0,30,505,2025-03-05,2.86,1,291,3,"23-ISTR-02823, 23-OSTR-02823"

In [10]:
new_orleans_listings.shape

(7444, 18)

In [11]:
new_orleans_listings.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='object')

In [12]:
new_orleans_listings.isnull().sum()

id                                   0
name                                 0
host_id                              0
host_name                            2
neighbourhood_group               7444
neighbourhood                        0
latitude                             0
longitude                            0
room_type                            0
price                             1211
minimum_nights                       0
number_of_reviews                    0
last_review                       1290
reviews_per_month                 1290
calculated_host_listings_count       0
availability_365                     0
number_of_reviews_ltm                0
license                           1335
dtype: int64

In [13]:
new_orleans_listings = new_orleans_listings.drop(columns=['neighbourhood_group'], errors='ignore')

In [14]:
new_orleans_listings['host_name'] = new_orleans_listings['host_name'].fillna("Unknown")

new_orleans_listings['reviews_per_month'] = new_orleans_listings['reviews_per_month'].fillna(0)

new_orleans_listings['last_review'] = new_orleans_listings['last_review'].fillna("No Review")

new_orleans_listings['price'] = new_orleans_listings['price'].fillna(new_orleans_listings['price'].median())

new_orleans_listings['license'] = new_orleans_listings['license'].fillna("Not Available")

In [15]:
new_orleans_listings.isnull().sum()

id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
number_of_reviews_ltm             0
license                           0
dtype: int64

In [16]:
chicago_listings['city'] = "Chicago"
new_orleans_listings['city'] = "New Orleans"

In [17]:
import pandas as pd

combined_listings = pd.concat([chicago_listings, new_orleans_listings])

In [18]:
combined_listings.shape

(16107, 18)

In [19]:
combined_listings['city'].value_counts()

city
Chicago        8663
New Orleans    7444
Name: count, dtype: int64

In [20]:
combined_listings.to_csv(
    r"E:\PowerBI_Projects\Airbnb_Dashboard_Project\cleaned_data\airbnb_combined_cleaned.csv",
    index=False
)

In [21]:
combined_listings.shape

(16107, 18)